### ISSUE TITLE
Logfile Output "optimize/minimize"

### ISSUE THREAD

**Issue by Jack0r** [kc5nra/VideoSourcePlugin#4]
Hey the last updates work very fine for me and I thought the only current annoyance I have are the very big log files when you use the video plugin a lot.

I would really love to see either all the log output moved to its own log file, or an option to toggle it maybe? :)

Keep up the good work!

**Comment by kc5nra** [comment]
Okay, until I can get around to making it's own configuration dialog (it's a global setting so it really doesn't belong in individual source configs) I've just disabled it.  The new release (1.0.43) contains the fix.
